version: 2

jobs:

  build-python27:
    docker:
      - image: 'python:2.7.13'
    steps:
      - checkout
      - run: pip install . ; python test.py; python module_test.py

  build-python34:
    docker:
      - image: 'python:3.4.9'
    steps:
      - checkout
      - run: pip install . ; python test.py; python module_test.py

  build-python35:
    docker:
      - image: 'python:3.5.3'
    steps:
      - checkout
      - run: pip install . ; python test.py; python module_test.py

  build-python36:
    docker:
      - image: 'python:3.6.0'
    steps:
      - checkout
      - run: pip install . ; python test.py; python module_test.py

  build-python37:
    docker:
      - image: 'python:3.7'
    steps:
      - checkout
      - run: pip install . ; python test.py; python module_test.py

workflows:
  version: 2
  build:
    jobs:
      - build-python27
      - build-python34
      - build-python35
      - build-python36
      - build-python37
